name: Regenerate PluginMaster
on:
  workflow_dispatch:
  repository_dispatch:
    types: [regenerate]
  push:
    branches:
      - main
  schedule:
    - cron: '55 5,11,17,23 * * *'  # Run at 05:55, 11:55, 17:55, 23:55 UTC
concurrency: regenerate
permissions:
  contents: write
  actions: read
jobs:
  generate:
    name: Regenerate PluginMaster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Generate PluginMaster
        run: python generate_pluginmaster.py
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Regenerate PluginMaster
